version: '3.7'
services:
    42069-backend:
        image: peem5210/42069:latest
        environment:
            - LAI_URL
            - LAI_TOKEN
            - TYPE
            - PROJECT_ID
            - PRIVATE_KEY_ID
            - PRIVATE_KEY
            - CLIENT_EMAIL
            - CLIENT_ID
            - AUTH_URI
            - TOKEN_URI
            - AUTH_PROVIDER_X509_CERT_URL
            - CLIENT_X509_CERT_URL
        networks:
            - 42069-backend-net
        container_name: "42069-backend-container"
        ports:
            - "8001:8000"
networks:
    42069-backend-net:
        name: "42069-net"
        driver_opts:
            com.docker.network.driver.mtu: 1400
#        external: true