version: '3.7'
services:
    42069-backend:
        build: .
        container_name: "42069-backend-container"
        ports:
            - "8001:8000"
        volumes:
            - ./42069:/42069
        restart: always
