version: '3.7'
services:
    42069-backend:
        build: .
        networks:
            - 42069-backend-net
        container_name: "42069-backend-container"
        ports:
            - "8001:8000"
        volumes:
            - .:/app
        restart: always
networks:
    42069-backend-net:
        name: "42069"