name: Manual deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[noBUILD]')"
    runs-on: self-hosted
    
    steps:
    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: set up docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - uses: actions/checkout@v2
    - name: buildpush
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/42069:latest

    - name: image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
  deploy:
    if: "! contains(toJSON(github.event.commits.*.message), '[noCD]')"
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: redeploy
        run: sh ./redeploy.sh
        env:
          LAI_URL: ${{ secrets.LAI_URL }}
          LAI_TOKEN: ${{ secrets.LAI_TOKEN }}
          TYPE: ${{ secrets.TYPE }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: "${{ secrets.PRIVATE_KEY }}"
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
          CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}