name: build docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[noCI]')"
    runs-on: self-hosted
    
    steps:
    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: set up docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - uses: actions/checkout@v2
    - name: buildpush
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/42069:latest

    - name: image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: redeploy
        run: curl localhost:9000/hooks/redeploy-webhook
